[workspace]
resolver = "2"
members = [
    "crates/cdsl-lsp",
    "crates/kernel-macros",
    "crates/kernel-registry",
    "crates/kernels/dsl",
    "crates/kernels/foundation",
    "crates/kernels/functions",
    "crates/kernels/ir",
    "crates/kernels/runtime",
    "crates/kernels/vm",
    "crates/tests",
    "crates/tools",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
