[package]
name = "continuum"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = [
    "crates/kernels/*",
    "crates/observers/*",
    "crates/dsl/*",
    "crates/tools",
    "crates/tests/*",
]
