[package]
name = "continuum-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = "2"
indexmap = "2"
rayon = "1"
continuum-foundation = { version = "0.1.0", path = "../foundation" }
tracing = "0.1.44"
