[package]
name = "continuum-dsl"
version.workspace = true
edition.workspace = true

[dependencies]
ariadne = "0.6.0"
chumsky = "0.12.0"
continuum-kernel-registry = { version = "0.1.0", path = "../../kernel-registry" }
logos = "0.16.0"

[dev-dependencies]
tempfile = "3.24.0"
