[package]
name = "continuum-kernel-types"
version = "0.1.0"
edition = "2021"

[dependencies]
linkme = "0.3"
serde = { version = "1.0", features = ["derive"] }

[lib]
path = "src/lib.rs"

[lints]
workspace = true
