[package]
name = "continuum-vm"
version.workspace = true
edition.workspace = true

[dependencies]
continuum-kernel-registry = { path = "../../kernel-registry" }
serde = { version = "1.0", features = ["derive"] }
