[package]
name = "continuum-vm"
version.workspace = true
edition.workspace = true

[dependencies]
continuum-foundation = { path = "../foundation" }
continuum-kernel-registry = { path = "../../kernel-registry" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
